### PR TITLE
update tool versions in tutorial markdown

### PR DESCRIPTION
**Pull request by sunyi000**
- updated tool versions for all modules
- include 'unzip' tool into the tutorial..(maybe not neccessary?)

### CODE REVIEW

**Comment by beatrizserrano** [comment]
@sunyi000 I think that you didn't push before making your changes?

**Comment by sunyi000** [comment]
> @sunyi000 I think that you didn't pull before making your changes?

it's 2 commits.. the last commit has the updates..github says no conflicts ....

**Comment by beatrizserrano** [comment]
ahh ok, but there are some things that have disappeared: [this section](https://github.com/beatrizserrano/training-material/pull/3/files#diff-de155769956ca42ef54a3cb44731698ef38e4a82adfee2533b65272141b925b5L42), the [link to the data in zenodo](https://github.com/beatrizserrano/training-material/pull/3/files#diff-de155769956ca42ef54a3cb44731698ef38e4a82adfee2533b65272141b925b5L70), this whole [new section](https://github.com/beatrizserrano/training-material/pull/3/files#diff-de155769956ca42ef54a3cb44731698ef38e4a82adfee2533b65272141b925b5L510)... what am I missing? :)

**Comment by sunyi000** [comment]
> ahh ok, but there are some things that have disappeared: [this section](https://github.com/beatrizserrano/training-material/pull/3/files#diff-de155769956ca42ef54a3cb44731698ef38e4a82adfee2533b65272141b925b5L42), the [link to the data in zenodo](https://github.com/beatrizserrano/training-material/pull/3/files#diff-de155769956ca42ef54a3cb44731698ef38e4a82adfee2533b65272141b925b5L70), this whole [new section](https://github.com/beatrizserrano/training-material/pull/3/files#diff-de155769956ca42ef54a3cb44731698ef38e4a82adfee2533b65272141b925b5L510)... what am I missing? :)

I guess it will merge with the latest instead of replacing it.. 
I will do it in another way, just pull and push back.. maybe easier.. 

cheers,

**Comment by beatrizserrano** [comment]
do we close this then @sunyi000? I've seen your commit to the branch...

**Comment by sunyi000** [comment]
> do we close this then @sunyi000? I've seen your commit to the branch...

yes I will close it ..cheers

**Pull request closed without merging**
